# ----
# Site

title: Richmond Greenway Film
url: "https://richmondgreenwayfilm.com"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Home of the Richmond Greenway Film
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Richmond Freenway Film
  links:
    - https://richmondgreenwayfilm.com

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  partner_orgs:
    _hide_content: true
    _icon: account_circle
  archive_items:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  #-
  #  scope:
  #    path: ""
  #    type: "staff_members"
  #  values:
  #    _options:
  #      image_path:
  #        width: 440
  #        height: 440
  #        uploads_dir: "/images/staff_members"
  -
    scope:
      path: ""
      type: "partner_orgs"
    values:
      _options:
        image_path:
          width: 440
          height: 440
          uploads_dir: "/images/staff_members"
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover